default_context:
  author_name: FT
  conda_path: ~/anaconda3/bin/conda
  default_branch: main
  description: 'Supporting materials for a course on mining complex networks based on the textbook. '
  module_name: src
  open_source_license: MIT
  project_name: Mining Complex Networks - Practical Methods for Mining Graphs using Python-igraph
  python_version: '3.7.9'
  repo_name: mining_graphs
  upstream_location: github.com
